name: Run Tests

on:
  push: # Run tests on every push
    branches: # Matches all branches
      - "*"
  pull_request: # Run tests on pull requests from all branches
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
